export const dataProduct = {
  "success": true,
  "data": {
    "data": [
      {
        "id": 899584,
        "seller_id": 627650,
        "game_id": 43,
        "item_type_id": 39,
        "server_id": 100,
        "item_info_id": 7286,
        "item_info_group_id": 72,
        "item_category_id": 4,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "TWD $200",
        "image_url": null,
        "description": "<span style=\"font-size:12pt;\"><strong>Dapat digunakan di INDONESIA.</strong></span>\n\n\nBagaimana cara mengisi Steam Wallet Code kedalam akun Steam saya?\n<span style=\"font-size:12pt;\"><strong>Ikuti langkah-langkah berikut untuk mengisi Steam Wallet Code anda kedalam akun Steam anda :</strong></span>\n<span style=\"font-size:12pt;\"><strong>1. Log in kedalam akun Steam anda</strong></span>\n<span style=\"font-size:12pt;\"><strong>2. Pada pojok kanan atas, silakan pilih Account Details.</strong></span>\n<span style=\"font-size:12pt;\"><strong>3. Pilih menu Add Funds to your Steam Wallet.</strong></span>\n<span style=\"font-size:12pt;\"><strong>4. Pilih Redeem a Steam Gift Card or Wallet Code.</strong></span>\n<span style=\"font-size:12pt;\"><strong>5. Masukkan kode voucher</strong></span>\n<span style=\"font-size:12pt;\"><strong>6. Klik Continue.</strong></span>\n<p> </p>",
        "meta_description": null,
        "price": 102700,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "steam-twd-200-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2020-08-26 21:49:34",
        "updated_at": "2021-09-06 07:40:28",
        "game": {
          "id": 43,
          "name": "Steam",
          "slug": "steam",
          "nickname": "Steam",
          "seo_string": "Steam",
          "publisher": "Valve",
          "is_active": 1,
          "is_strict_item_info": 0,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari Transaksi Langsung Dengan Penjual\r\nGunakan Fitur Pesan itemku Dalam Berkomunikasi Dengan Penjual",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20170621/594a01f1d0f72.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20181011/5bbee923cdb0d.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20161109/5822fd0b9d20d.png",
          "small_icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20181011/5bbeea8e0d694.png",
          "description": "Tempat Jual-Beli Voucher Game no.1 di Indonesia, paling murah dan terpercaya. Pembelian berbagai macam jenis dan nominal Steam Wallet tersedia di itemku.\r\n<br><br>\r\nTersedia Steam Wallet Code IDR dengan nominal Rupiah dan Steam Wallet Code US dengan nominal Dollar. Steam Wallet Code yang kamu beli dapat kamu redeem secara langsung di platform Steam.\r\n<br><br>\r\nTersedia juga Steam Games terbaik dengan harga termurah. Beli Steam Games secara online di itemku dan download gamenya di platform Steam tanpa perlu backup.\r\n<br><br>\r\nBelanja di itemku sangat aman dan mudah dengan itemku Safe Trading, juga cepat dan praktis verifikasi otomatis 24 jam.\r\nPembayaran tersedia melalui ATM dengan Virtual Account, Cash/Tunai melalui Indomaret, Alfamart, Pegadaian & Kantor Pos, Pulsa Telkomsel, Indosat & XL, serta dengan menggunakan Dana Dompetku.",
          "template_description": "https://itemku.com/tanya-jawab/artikel/cara-trading-voucher-steam-wallet-code/232066807 <hr>",
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-voucher-steam-wallet-code/232066807",
          "platform_id": null,
          "game_official_store_id": 10,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 39,
          "game_id": 43,
          "name": "Steam Wallet",
          "slug": "steam-wallet",
          "seo_string": "Steam Wallet",
          "description": "Steam Wallet",
          "trade_link": "",
          "sequence": 39,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 1,
          "max_codes": 1,
          "how_to_trade_faq_id": "232066807",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 1,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 2,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 6,
          "allow_image_subtitle": 0,
          "maximum_image_upload": 3,
          "item_category_id": 4,
          "withdrawable_day": 0,
          "is_subscription": 1,
          "risky_type_id": 0,
          "is_using_denom": 1,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": 0,
          "is_using_order_info": 1,
          "ip_address": null,
          "required_info": null
        },
        "item_info": {
          "id": 7286,
          "name": "TWD $200",
          "slug": "twd-200",
          "game_id": 43,
          "item_type_id": 39,
          "item_info_group_id": 72,
          "base_unit": 1,
          "max_order": 0,
          "nominal_value": 200,
          "description": "",
          "is_active": 1
        },
        "order_record": {
          "product_id": 899584,
          "successful_order_count": 154,
          "failed_order_count": 0
        },
        "stock": 2,
        "view_count": 1015,
        "images": [
          {
            "id": 1852044,
            "product_id": 899584,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200826/e87ddcf2c887eb1f6a7e04f875895d12e1ba0d7e51a324c4ddf1050a46a3fc29.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200826/e87ddcf2c887eb1f6a7e04f875895d12e1ba0d7e51a324c4ddf1050a46a3fc29_thumb.jpg",
            "image_title": "",
            "image_text": "",
            "is_active": 1,
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200826/e87ddcf2c887eb1f6a7e04f875895d12e1ba0d7e51a324c4ddf1050a46a3fc29.webp",
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200826/e87ddcf2c887eb1f6a7e04f875895d12e1ba0d7e51a324c4ddf1050a46a3fc29_thumb.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": 99000,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 0,
        "rarity_type_id": null,
        "suggested_price": 109300,
        "use_fast_delivery": 0,
        "use_ads": 0
      },
      {
        "id": 1270946,
        "seller_id": 627650,
        "game_id": 81,
        "item_type_id": 193,
        "server_id": 182,
        "item_info_id": 23846,
        "item_info_group_id": 24,
        "item_category_id": 4,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "US$ 100",
        "image_url": null,
        "description": "<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Cara Menukarkan Kode Xbox Live Gift Card:</strong></span>\n<span style=\"font-size:12pt;\"><strong>Melalui Console XBOX ONE</strong></span>\n<span style=\"font-size:12pt;\"><strong>1. Dari home screen, pilih “Games”</strong></span>\n<span style=\"font-size:12pt;\"><strong>2. Pilih “Use a code”</strong></span>\n<span style=\"font-size:12pt;\"><strong>3. Sign in jika diminta, kemudian masukan 25 digit kode dan klik “Confirm” (Kode harus diketik MANUAL, bukan secara copy paste)</strong></span>\n<span style=\"font-size:12pt;\"><strong>4. Masukan Alamat jika diminta oleh sistem. Untuk alamat US dapat menggunakan data alamat pada tutorial di atas.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Melalui Console XBOX 360</strong></span>\n<span style=\"font-size:12pt;\"><strong>1. Sign in pada XBOX Live</strong></span>\n<span style=\"font-size:12pt;\"><strong>2. Tekan tombol “Guide” pada controller (Tombol berbentuk bola berlogo X pada tengah controller)</strong></span>\n<span style=\"font-size:12pt;\"><strong>3. Pilih menu “Games &amp; Aps” dan pilih “Redeem Code”</strong></span>\n<span style=\"font-size:12pt;\"><strong>4. Masukan 25 digit kode,klik “Done” lalu”Yes” (Kode harus diketik MANUAL, bukan secara copy paste)</strong></span>\n<span style=\"font-size:12pt;\"><strong>5. Masukan Alamat jika diminta oleh sistem. Untuk alamat US dapat menggunakan data alamat pada tutorial di atas.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Melalui PC</strong></span>\n<span style=\"font-size:12pt;\"><strong>1. Masuk ke https://live.xbox.com/redeemtoken dan Sign In</strong></span>\n<span style=\"font-size:12pt;\"><strong>2. Klik “Redeem”</strong></span>\n<span style=\"font-size:12pt;\"><strong>3. Masukan 25 digit kode dan klik “Confirm” (Kode harus diketik MANUAL, bukan secara copy paste)</strong></span>\n<span style=\"font-size:12pt;\"><strong>4. Masukan Alamat jika diminta oleh sistem. Untuk alamat US dapat menggunakan data alamat pada tutorial di atas.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Untuk tutorial resmi dari Xbox, silakan cek di https://support.xbox.com/en-US/billing/prepaid-codes/redeem-prepaid-codes</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Cara melihat saldo account Xbox Live : </strong></span>\n<span style=\"font-size:12pt;\"><strong>https://support.xbox.com/en-US/my-account/microsoft-account/check-your-microsoft-account-balance</strong></span></p>",
        "meta_description": null,
        "price": 1342000,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "xbox-gift-card-us-100-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2021-06-28 18:09:13",
        "updated_at": "2021-09-03 11:20:06",
        "game": {
          "id": 81,
          "name": "Xbox Gift Card",
          "slug": "xbox-gift-card",
          "nickname": "Xbox Gift Card",
          "seo_string": "Xbox",
          "publisher": "xbox",
          "is_active": 1,
          "is_strict_item_info": 0,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari Transaksi Langsung Dengan Penjual\r\nGunakan Fitur Pesan itemku Dalam Berkomunikasi Dengan Penjual",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20180515/5afab24db3253.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20190221/5c6e7ed84fccb.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20180515/5afab24d7c80c.png",
          "small_icon_image_url": null,
          "description": "Tempat Jual-Beli Xbox Gift Card no.1 di Indonesia, paling murah dan terpercaya. Tersedia Xbox Gift Card mulai dari US$ 10 sampai US$ 50. Belanja di itemku sangat aman dan mudah dengan itemku Safe Trading, juga cepat dan praktis verifikasi otomatis 24 jam. Pembayaran tersedia melalui ATM dengan Virtual Account, Cash/Tunai melalui Indomaret, Alfamart, Pegadaian & Kantor Pos, Pulsa Telkomsel, Indosat & XL, serta dengan menggunakan Dana Dompetku.",
          "template_description": "https://itemku.com/tanya-jawab/artikel/cara-trading-e-voucher/235260387 <hr>",
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-e-voucher/235260387",
          "platform_id": null,
          "game_official_store_id": 0,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 193,
          "game_id": 81,
          "name": "Gift Card",
          "slug": "gift-card",
          "seo_string": null,
          "description": null,
          "trade_link": null,
          "sequence": 193,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 1,
          "max_codes": 1,
          "how_to_trade_faq_id": "115003121488",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 1,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 2,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 1,
          "allow_image_subtitle": 0,
          "maximum_image_upload": 3,
          "item_category_id": 4,
          "withdrawable_day": 0,
          "is_subscription": 1,
          "risky_type_id": 0,
          "is_using_denom": 1,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": 0,
          "is_using_order_info": 1,
          "ip_address": null,
          "required_info": null
        },
        "item_info": {
          "id": 23846,
          "name": "US$ 100",
          "slug": "us-100",
          "game_id": 81,
          "item_type_id": 193,
          "item_info_group_id": 24,
          "base_unit": 1,
          "max_order": 0,
          "nominal_value": 100,
          "description": null,
          "is_active": 1
        },
        "order_record": {
          "product_id": 1270946,
          "successful_order_count": 2,
          "failed_order_count": 0
        },
        "stock": 1,
        "view_count": 53,
        "images": [
          {
            "id": 2566060,
            "product_id": 1270946,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/itemku-upload/2021628/jbuhzd4lrii85nkh2cgsv6.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/itemku-upload/2021628/jbuhzd4lrii85nkh2cgsv6_thumbnail.jpg",
            "image_title": "",
            "image_text": "",
            "is_active": 1,
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/itemku-upload/2021628/jbuhzd4lrii85nkh2cgsv6.webp",
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/itemku-upload/2021628/jbuhzd4lrii85nkh2cgsv6_thumbnail.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": 1420900,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 0,
        "rarity_type_id": null,
        "suggested_price": 0,
        "use_fast_delivery": 0,
        "use_ads": 0
      },
      {
        "id": 812980,
        "seller_id": 627650,
        "game_id": 154,
        "item_type_id": 405,
        "server_id": 264,
        "item_info_id": 9208,
        "item_info_group_id": 133,
        "item_category_id": 4,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "USD $5",
        "image_url": null,
        "description": "NOTE : Hanya Bisa digunakan pada Microsoft Account Region United States\n\nCara Redeem: https://support.microsoft.com/en-us/help/10604/microsoft-account-redeem-gift-card-or-code\n\nCara cek microsoft account nya US:\n1. Sign in ke https://account.microsoft.com\n2. Kemudian pilih Payment &amp; Billing &gt; Billing Info\n3. Jika ada tulisan US - Personal Account maka account nya US\n\nhttps://support.microsoft.com/en-us/help/4027266/microsoft-store-change-your-region",
        "meta_description": null,
        "price": 72800,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "windows-gift-card-usd-5-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2020-06-18 17:06:16",
        "updated_at": "2021-08-12 11:03:27",
        "game": {
          "id": 154,
          "name": "Windows Gift Card",
          "slug": "windows-gift-card",
          "nickname": "Windows Gift Card",
          "seo_string": "Windows Gift Card",
          "publisher": "Microsoft",
          "is_active": 1,
          "is_strict_item_info": 1,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari transaksi langsung dengan Penjual. Selalu gunakan Fitur Pesan itemku untuk berkomunikasi.",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020123/vprvh4jg38yk87k6fzr9p.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020123/seaouc03qsfc2t7exs7jv.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020123/wlyx7rm97cp2wqc02ya6.png",
          "small_icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020123/wlyx7rm97cp2wqc02ya6_thumbnail.png",
          "description": "Belanja Aplikasi/Software, Game, atau E-Book tidak lagi sulit dengan adanya Windows Store. Gunakan Voucher Windows Gift Card untuk belanja langsung.",
          "template_description": null,
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-microsoft-gift-card/360038679712",
          "platform_id": null,
          "game_official_store_id": 0,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 405,
          "game_id": 154,
          "name": "Gift Card",
          "slug": "gift-card",
          "seo_string": null,
          "description": null,
          "trade_link": null,
          "sequence": 99,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 0,
          "max_codes": 1,
          "how_to_trade_faq_id": "360038679712",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 0,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 2,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 1,
          "allow_image_subtitle": 0,
          "maximum_image_upload": 3,
          "item_category_id": 4,
          "withdrawable_day": 0,
          "is_subscription": 1,
          "risky_type_id": 0,
          "is_using_denom": 1,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": null,
          "is_using_order_info": 1,
          "ip_address": null,
          "required_info": null
        },
        "item_info": {
          "id": 9208,
          "name": "USD $5",
          "slug": "usd-5",
          "game_id": 154,
          "item_type_id": 405,
          "item_info_group_id": 133,
          "base_unit": 1,
          "max_order": 0,
          "nominal_value": 5,
          "description": null,
          "is_active": 1
        },
        "order_record": {
          "product_id": 812980,
          "successful_order_count": 97,
          "failed_order_count": 0
        },
        "stock": 1,
        "view_count": 848,
        "images": [
          {
            "id": 1802534,
            "product_id": 812980,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/28fc8e027b28c0dbcf90a79020871450608b6c448c3c3f8d1ebd6d3f1961c88e.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/28fc8e027b28c0dbcf90a79020871450608b6c448c3c3f8d1ebd6d3f1961c88e_thumb.jpg",
            "image_title": null,
            "image_text": null,
            "is_active": 1,
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/28fc8e027b28c0dbcf90a79020871450608b6c448c3c3f8d1ebd6d3f1961c88e_thumb.webp",
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/28fc8e027b28c0dbcf90a79020871450608b6c448c3c3f8d1ebd6d3f1961c88e.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": null,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 0,
        "rarity_type_id": null,
        "suggested_price": 0,
        "use_fast_delivery": 0,
        "use_ads": 0
      },
      {
        "id": 818233,
        "seller_id": 627650,
        "game_id": 171,
        "item_type_id": 433,
        "server_id": 310,
        "item_info_id": 9446,
        "item_info_group_id": 155,
        "item_category_id": 4,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "US $20",
        "image_url": null,
        "description": "Cara Trading Battle.net Gift Card\n\n1. Pilih dagangan dan lakukan pembelian\n2. Terima kode voucher dari penjual\n3. Login ke Battle.net melalui website atau aplikasi\n4. Klik Profile kamu yang terletak di kanan atas\n5. Pilih Redeem A Code dari dropdown menu yang tersedia\n6. Masukkan kode yang sudah kamu terima dari penjual lalu tekan tombol Redeem Code\n7. Periksa apakah Battle.net Balance kamu sudah bertambah sesuai dengan yang kamu beli\n8. Jika sudah sesuai, klik Selesai untuk menyelesaikan pesanan kamu",
        "meta_description": null,
        "price": 283800,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "battlenet-us-20-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2020-06-22 16:07:26",
        "updated_at": "2021-09-06 07:40:28",
        "game": {
          "id": 171,
          "name": "Battle.net",
          "slug": "battlenet",
          "nickname": "Battle Net",
          "seo_string": "blizzard battle net",
          "publisher": "Activision Blizzard",
          "is_active": 1,
          "is_strict_item_info": 0,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari transaksi langsung dengan Penjual. Selalu gunakan Fitur Pesan itemku untuk berkomunikasi.",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020327/yutvah6otn3on8bkmi4l6.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020327/ty53gi4v148yzk7f08ikff.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020327/2wsdkejiafxaj71qg5950c.png",
          "small_icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020327/2wsdkejiafxaj71qg5950c_thumbnail.png",
          "description": "Battle.net adalah platform game seperti Steam yang dimiliki oleh Activision Blizzard. Mainkan game-game keluaran Blizzard dan Activision seperti World of Warcraft, Overwatch, Call of Duty (CoD). Gunakan voucher Battle.net gift card untuk belanja game atau kebutuh skin, kosmetik, dan Battle Pass kamu.",
          "template_description": null,
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-battle.net/360041562971",
          "platform_id": null,
          "game_official_store_id": 9,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 433,
          "game_id": 171,
          "name": "Gift Card",
          "slug": "gift-card",
          "seo_string": null,
          "description": null,
          "trade_link": null,
          "sequence": 99,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 0,
          "max_codes": 1,
          "how_to_trade_faq_id": "360041562971",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 0,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 2,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 1,
          "allow_image_subtitle": 1,
          "maximum_image_upload": 3,
          "item_category_id": 4,
          "withdrawable_day": 0,
          "is_subscription": 1,
          "risky_type_id": 0,
          "is_using_denom": 1,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": null,
          "is_using_order_info": 1,
          "ip_address": null,
          "required_info": null
        },
        "item_info": {
          "id": 9446,
          "name": "US $20",
          "slug": "us-20",
          "game_id": 171,
          "item_type_id": 433,
          "item_info_group_id": 155,
          "base_unit": 1,
          "max_order": 0,
          "nominal_value": 20,
          "description": null,
          "is_active": 1
        },
        "order_record": {
          "product_id": 818233,
          "successful_order_count": 429,
          "failed_order_count": 0
        },
        "stock": 2,
        "view_count": 1351,
        "images": [
          {
            "id": 1802543,
            "product_id": 818233,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/8c4516ad3ac725a8113c31549c21d4c8b385a36b027a6650bacf64819e347b8c.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/8c4516ad3ac725a8113c31549c21d4c8b385a36b027a6650bacf64819e347b8c_thumb.jpg",
            "image_title": "battlenet",
            "image_text": "",
            "is_active": 1,
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/8c4516ad3ac725a8113c31549c21d4c8b385a36b027a6650bacf64819e347b8c.webp",
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/8c4516ad3ac725a8113c31549c21d4c8b385a36b027a6650bacf64819e347b8c_thumb.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": 327000,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 1,
        "rarity_type_id": null,
        "suggested_price": 0,
        "use_fast_delivery": 0,
        "use_ads": 0
      },
      {
        "id": 378138,
        "seller_id": 627650,
        "game_id": 81,
        "item_type_id": 193,
        "server_id": 182,
        "item_info_id": 4936,
        "item_info_group_id": 24,
        "item_category_id": 4,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "US$ 25",
        "image_url": null,
        "description": "<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Cara Menukarkan Kode Xbox Live Gift Card:</strong></span>\n<span style=\"font-size:12pt;\"><strong>Melalui Console XBOX ONE</strong></span>\n<span style=\"font-size:12pt;\"><strong>1. Dari home screen, pilih “Games”</strong></span>\n<span style=\"font-size:12pt;\"><strong>2. Pilih “Use a code”</strong></span>\n<span style=\"font-size:12pt;\"><strong>3. Sign in jika diminta, kemudian masukan 25 digit kode dan klik “Confirm” (Kode harus diketik MANUAL, bukan secara copy paste)</strong></span>\n<span style=\"font-size:12pt;\"><strong>4. Masukan Alamat jika diminta oleh sistem. Untuk alamat US dapat menggunakan data alamat pada tutorial di atas.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Melalui Console XBOX 360</strong></span>\n<span style=\"font-size:12pt;\"><strong>1. Sign in pada XBOX Live</strong></span>\n<span style=\"font-size:12pt;\"><strong>2. Tekan tombol “Guide” pada controller (Tombol berbentuk bola berlogo X pada tengah controller)</strong></span>\n<span style=\"font-size:12pt;\"><strong>3. Pilih menu “Games &amp; Aps” dan pilih “Redeem Code”</strong></span>\n<span style=\"font-size:12pt;\"><strong>4. Masukan 25 digit kode,klik “Done” lalu”Yes” (Kode harus diketik MANUAL, bukan secara copy paste)</strong></span>\n<span style=\"font-size:12pt;\"><strong>5. Masukan Alamat jika diminta oleh sistem. Untuk alamat US dapat menggunakan data alamat pada tutorial di atas.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Melalui PC</strong></span>\n<span style=\"font-size:12pt;\"><strong>1. Masuk ke https://live.xbox.com/redeemtoken dan Sign In</strong></span>\n<span style=\"font-size:12pt;\"><strong>2. Klik “Redeem”</strong></span>\n<span style=\"font-size:12pt;\"><strong>3. Masukan 25 digit kode dan klik “Confirm” (Kode harus diketik MANUAL, bukan secara copy paste)</strong></span>\n<span style=\"font-size:12pt;\"><strong>4. Masukan Alamat jika diminta oleh sistem. Untuk alamat US dapat menggunakan data alamat pada tutorial di atas.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Untuk tutorial resmi dari Xbox, silakan cek di https://support.xbox.com/en-US/billing/prepaid-codes/redeem-prepaid-codes</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Cara melihat saldo account Xbox Live : </strong></span>\n<span style=\"font-size:12pt;\"><strong>https://support.xbox.com/en-US/my-account/microsoft-account/check-your-microsoft-account-balance</strong></span></p>",
        "meta_description": null,
        "price": 335900,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "xbox-gift-card-us-25-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2018-05-23 21:06:17",
        "updated_at": "2021-09-04 08:47:16",
        "game": {
          "id": 81,
          "name": "Xbox Gift Card",
          "slug": "xbox-gift-card",
          "nickname": "Xbox Gift Card",
          "seo_string": "Xbox",
          "publisher": "xbox",
          "is_active": 1,
          "is_strict_item_info": 0,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari Transaksi Langsung Dengan Penjual\r\nGunakan Fitur Pesan itemku Dalam Berkomunikasi Dengan Penjual",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20180515/5afab24db3253.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20190221/5c6e7ed84fccb.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20180515/5afab24d7c80c.png",
          "small_icon_image_url": null,
          "description": "Tempat Jual-Beli Xbox Gift Card no.1 di Indonesia, paling murah dan terpercaya. Tersedia Xbox Gift Card mulai dari US$ 10 sampai US$ 50. Belanja di itemku sangat aman dan mudah dengan itemku Safe Trading, juga cepat dan praktis verifikasi otomatis 24 jam. Pembayaran tersedia melalui ATM dengan Virtual Account, Cash/Tunai melalui Indomaret, Alfamart, Pegadaian & Kantor Pos, Pulsa Telkomsel, Indosat & XL, serta dengan menggunakan Dana Dompetku.",
          "template_description": "https://itemku.com/tanya-jawab/artikel/cara-trading-e-voucher/235260387 <hr>",
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-e-voucher/235260387",
          "platform_id": null,
          "game_official_store_id": 0,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 193,
          "game_id": 81,
          "name": "Gift Card",
          "slug": "gift-card",
          "seo_string": null,
          "description": null,
          "trade_link": null,
          "sequence": 193,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 1,
          "max_codes": 1,
          "how_to_trade_faq_id": "115003121488",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 1,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 2,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 1,
          "allow_image_subtitle": 0,
          "maximum_image_upload": 3,
          "item_category_id": 4,
          "withdrawable_day": 0,
          "is_subscription": 1,
          "risky_type_id": 0,
          "is_using_denom": 1,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": 0,
          "is_using_order_info": 1,
          "ip_address": null,
          "required_info": null
        },
        "item_info": {
          "id": 4936,
          "name": "US$ 25",
          "slug": "us-25",
          "game_id": 81,
          "item_type_id": 193,
          "item_info_group_id": 24,
          "base_unit": 1,
          "max_order": 0,
          "nominal_value": 25,
          "description": "",
          "is_active": 1
        },
        "order_record": {
          "product_id": 378138,
          "successful_order_count": 64,
          "failed_order_count": 0
        },
        "stock": 1,
        "view_count": 1171,
        "images": [
          {
            "id": 1802516,
            "product_id": 378138,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/c985a118eb394c38b273a27f910cf6253536fe2e1dc2380754f3f6a4e1bb44a3.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/c985a118eb394c38b273a27f910cf6253536fe2e1dc2380754f3f6a4e1bb44a3_thumb.jpg",
            "image_title": null,
            "image_text": null,
            "is_active": 1,
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/c985a118eb394c38b273a27f910cf6253536fe2e1dc2380754f3f6a4e1bb44a3.webp",
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/c985a118eb394c38b273a27f910cf6253536fe2e1dc2380754f3f6a4e1bb44a3_thumb.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": 354300,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 0,
        "rarity_type_id": null,
        "suggested_price": 0,
        "use_fast_delivery": 0,
        "use_ads": 0
      },
      {
        "id": 354213,
        "seller_id": 627650,
        "game_id": 43,
        "item_type_id": 240,
        "server_id": 100,
        "item_info_id": null,
        "item_info_group_id": null,
        "item_category_id": 6,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "Random GOLD PREMIUM Steam Key Global 1 Key",
        "image_url": null,
        "description": "Cara Aktivasi Steam Game Key :\n1. Buka Steam Launcher\n2. Pilih Menu Games diatas\n3. Pilih \"Activate a product on steam\"\n4. Klik NEXT, kemudian klik Agree\n5. Masukan kode GAME CD KEY yang sudah diberikan\n6. NEXT Ikutin Sampai Selesai",
        "meta_description": "",
        "price": 14000,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "steam-random-gold-premium-steam-key-global-1-key-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2018-04-03 23:12:24",
        "updated_at": "2021-05-21 07:33:54",
        "game": {
          "id": 43,
          "name": "Steam",
          "slug": "steam",
          "nickname": "Steam",
          "seo_string": "Steam",
          "publisher": "Valve",
          "is_active": 1,
          "is_strict_item_info": 0,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari Transaksi Langsung Dengan Penjual\r\nGunakan Fitur Pesan itemku Dalam Berkomunikasi Dengan Penjual",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20170621/594a01f1d0f72.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20181011/5bbee923cdb0d.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20161109/5822fd0b9d20d.png",
          "small_icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20181011/5bbeea8e0d694.png",
          "description": "Tempat Jual-Beli Voucher Game no.1 di Indonesia, paling murah dan terpercaya. Pembelian berbagai macam jenis dan nominal Steam Wallet tersedia di itemku.\r\n<br><br>\r\nTersedia Steam Wallet Code IDR dengan nominal Rupiah dan Steam Wallet Code US dengan nominal Dollar. Steam Wallet Code yang kamu beli dapat kamu redeem secara langsung di platform Steam.\r\n<br><br>\r\nTersedia juga Steam Games terbaik dengan harga termurah. Beli Steam Games secara online di itemku dan download gamenya di platform Steam tanpa perlu backup.\r\n<br><br>\r\nBelanja di itemku sangat aman dan mudah dengan itemku Safe Trading, juga cepat dan praktis verifikasi otomatis 24 jam.\r\nPembayaran tersedia melalui ATM dengan Virtual Account, Cash/Tunai melalui Indomaret, Alfamart, Pegadaian & Kantor Pos, Pulsa Telkomsel, Indosat & XL, serta dengan menggunakan Dana Dompetku.",
          "template_description": "https://itemku.com/tanya-jawab/artikel/cara-trading-voucher-steam-wallet-code/232066807 <hr>",
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-voucher-steam-wallet-code/232066807",
          "platform_id": null,
          "game_official_store_id": 10,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 240,
          "game_id": 43,
          "name": "Game Key",
          "slug": "game-key",
          "seo_string": null,
          "description": null,
          "trade_link": null,
          "sequence": 240,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 0,
          "max_codes": 1,
          "how_to_trade_faq_id": "231739267",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 1,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 5,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 5,
          "allow_image_subtitle": 0,
          "maximum_image_upload": 3,
          "item_category_id": 6,
          "withdrawable_day": 0,
          "is_subscription": 0,
          "risky_type_id": 0,
          "is_using_denom": 0,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": 0,
          "is_using_order_info": 0,
          "ip_address": null,
          "required_info": null
        },
        "item_info": null,
        "order_record": {
          "product_id": 354213,
          "successful_order_count": 1876,
          "failed_order_count": 0
        },
        "stock": 9,
        "view_count": 17481,
        "images": [
          {
            "id": 1802510,
            "product_id": 354213,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/f71540b62a300cf0b01f0b74ab3f34b8cfc89738afd31ce5c1a2c055b8b35750.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/f71540b62a300cf0b01f0b74ab3f34b8cfc89738afd31ce5c1a2c055b8b35750_thumb.jpg",
            "image_title": null,
            "image_text": null,
            "is_active": 1,
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/f71540b62a300cf0b01f0b74ab3f34b8cfc89738afd31ce5c1a2c055b8b35750_thumb.webp",
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/f71540b62a300cf0b01f0b74ab3f34b8cfc89738afd31ce5c1a2c055b8b35750.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": null,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 0,
        "rarity_type_id": null,
        "suggested_price": 0,
        "use_fast_delivery": 0,
        "use_ads": 0
      },
      {
        "id": 660636,
        "seller_id": 627650,
        "game_id": 148,
        "item_type_id": 402,
        "server_id": 259,
        "item_info_id": 9165,
        "item_info_group_id": 123,
        "item_category_id": 4,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "USD $50",
        "image_url": null,
        "description": "* Nintendo eShop Prepaid Card (US) hanya bisa digunakan untuk Nintendo Account Region U.S.\n* Bisa dipakai untuk : Nintendo Switch , Nintendo Wii U , Nintendo 3DS\n\nBagaimana cara redeem Nintendo eShop Prepaid Card?\n1. Pilih Icon Nintendo eShop di menu HOME.\n2. Geser ke kiri lalu pilih Add Funds.\n3. Pilih Redeem a Nintendo eShop Card.\n4. Masukkan 16 digit kode aktivasi yang terdapat di bagian belakang kartu voucher Anda, kemudian pilih “OK” untuk melengkapi transaksi.",
        "meta_description": null,
        "price": 679700,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "nintendo-eshop-card-usd-50-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2020-01-19 00:05:12",
        "updated_at": "2021-09-01 07:31:39",
        "game": {
          "id": 148,
          "name": "Nintendo eShop Card",
          "slug": "nintendo-eshop-card",
          "nickname": "Nintendo eShop",
          "seo_string": "voucher nintendo eshop card",
          "publisher": "Nintendo",
          "is_active": 1,
          "is_strict_item_info": 0,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari transaksi langsung dengan Penjual. Selalu gunakan Fitur Pesan itemku untuk berkomunikasi.",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020117/wj42ucu4kra4v0hezq85g4.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020117/b7w2si8x7dlbbgh06l65pl.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020117/bam1o972rnk28h3qaqvqj9.png",
          "small_icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020117/bam1o972rnk28h3qaqvqj9_thumbnail.png",
          "description": "Beli game-game Nintendo favorit kamu langsung dari Nintendo eShop. Zelda Breath of the Wild, Pokemon Sword and Shield, atau Splatoon sudah siap menanti kamu.",
          "template_description": null,
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-nintendo-eshop-card/360038933131",
          "platform_id": null,
          "game_official_store_id": 0,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 402,
          "game_id": 148,
          "name": "Gift Card",
          "slug": "gift-card",
          "seo_string": null,
          "description": null,
          "trade_link": null,
          "sequence": 99,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 0,
          "max_codes": 1,
          "how_to_trade_faq_id": "360038933131",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 0,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 2,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 1,
          "allow_image_subtitle": 0,
          "maximum_image_upload": 3,
          "item_category_id": 4,
          "withdrawable_day": 0,
          "is_subscription": 1,
          "risky_type_id": 0,
          "is_using_denom": 1,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": null,
          "is_using_order_info": 1,
          "ip_address": null,
          "required_info": null
        },
        "item_info": {
          "id": 9165,
          "name": "USD $50",
          "slug": "usd-50",
          "game_id": 148,
          "item_type_id": 402,
          "item_info_group_id": 123,
          "base_unit": 1,
          "max_order": 0,
          "nominal_value": 50,
          "description": null,
          "is_active": 1
        },
        "order_record": {
          "product_id": 660636,
          "successful_order_count": 265,
          "failed_order_count": 0
        },
        "stock": 1,
        "view_count": 1380,
        "images": [
          {
            "id": 1802532,
            "product_id": 660636,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/d67e044ce4c59089b25090c4bf2678ea9ddfb67de4e255c2c84dccecaf37613e.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/d67e044ce4c59089b25090c4bf2678ea9ddfb67de4e255c2c84dccecaf37613e_thumb.jpg",
            "image_title": null,
            "image_text": null,
            "is_active": 1,
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/d67e044ce4c59089b25090c4bf2678ea9ddfb67de4e255c2c84dccecaf37613e.webp",
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/d67e044ce4c59089b25090c4bf2678ea9ddfb67de4e255c2c84dccecaf37613e_thumb.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": 789000,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 1,
        "rarity_type_id": null,
        "suggested_price": 0,
        "use_fast_delivery": 0,
        "use_ads": 0
      },
      {
        "id": 812984,
        "seller_id": 627650,
        "game_id": 154,
        "item_type_id": 405,
        "server_id": 264,
        "item_info_id": 9210,
        "item_info_group_id": 133,
        "item_category_id": 4,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "USD $15",
        "image_url": null,
        "description": "NOTE : Hanya Bisa digunakan pada Microsoft Account Region United States\n\nCara Redeem: https://support.microsoft.com/en-us/help/10604/microsoft-account-redeem-gift-card-or-code\n\nCara cek microsoft account nya US:\n1. Sign in ke https://account.microsoft.com\n2. Kemudian pilih Payment &amp; Billing &gt; Billing Info\n3. Jika ada tulisan US - Personal Account maka account nya US\n\nhttps://support.microsoft.com/en-us/help/4027266/microsoft-store-change-your-region",
        "meta_description": null,
        "price": 199900,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "windows-gift-card-usd-15-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2020-06-18 17:07:21",
        "updated_at": "2021-09-06 07:40:28",
        "game": {
          "id": 154,
          "name": "Windows Gift Card",
          "slug": "windows-gift-card",
          "nickname": "Windows Gift Card",
          "seo_string": "Windows Gift Card",
          "publisher": "Microsoft",
          "is_active": 1,
          "is_strict_item_info": 1,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari transaksi langsung dengan Penjual. Selalu gunakan Fitur Pesan itemku untuk berkomunikasi.",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020123/vprvh4jg38yk87k6fzr9p.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020123/seaouc03qsfc2t7exs7jv.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020123/wlyx7rm97cp2wqc02ya6.png",
          "small_icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020123/wlyx7rm97cp2wqc02ya6_thumbnail.png",
          "description": "Belanja Aplikasi/Software, Game, atau E-Book tidak lagi sulit dengan adanya Windows Store. Gunakan Voucher Windows Gift Card untuk belanja langsung.",
          "template_description": null,
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-microsoft-gift-card/360038679712",
          "platform_id": null,
          "game_official_store_id": 0,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 405,
          "game_id": 154,
          "name": "Gift Card",
          "slug": "gift-card",
          "seo_string": null,
          "description": null,
          "trade_link": null,
          "sequence": 99,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 0,
          "max_codes": 1,
          "how_to_trade_faq_id": "360038679712",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 0,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 2,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 1,
          "allow_image_subtitle": 0,
          "maximum_image_upload": 3,
          "item_category_id": 4,
          "withdrawable_day": 0,
          "is_subscription": 1,
          "risky_type_id": 0,
          "is_using_denom": 1,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": null,
          "is_using_order_info": 1,
          "ip_address": null,
          "required_info": null
        },
        "item_info": {
          "id": 9210,
          "name": "USD $15",
          "slug": "usd-15",
          "game_id": 154,
          "item_type_id": 405,
          "item_info_group_id": 133,
          "base_unit": 1,
          "max_order": 0,
          "nominal_value": 15,
          "description": null,
          "is_active": 1
        },
        "order_record": {
          "product_id": 812984,
          "successful_order_count": 51,
          "failed_order_count": 0
        },
        "stock": 1,
        "view_count": 381,
        "images": [
          {
            "id": 1802536,
            "product_id": 812984,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/a1d4d9e57d60e9fa8cd2443a42e0d08d394b488b0f2bc0e8c8c8357cef1e3d84.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/a1d4d9e57d60e9fa8cd2443a42e0d08d394b488b0f2bc0e8c8c8357cef1e3d84_thumb.jpg",
            "image_title": null,
            "image_text": null,
            "is_active": 1,
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/a1d4d9e57d60e9fa8cd2443a42e0d08d394b488b0f2bc0e8c8c8357cef1e3d84_thumb.webp",
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/a1d4d9e57d60e9fa8cd2443a42e0d08d394b488b0f2bc0e8c8c8357cef1e3d84.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": null,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 0,
        "rarity_type_id": null,
        "suggested_price": 0,
        "use_fast_delivery": 0,
        "use_ads": 0
      },
      {
        "id": 369842,
        "seller_id": 627650,
        "game_id": 80,
        "item_type_id": 196,
        "server_id": 181,
        "item_info_id": 4927,
        "item_info_group_id": 30,
        "item_category_id": 4,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "US$ 50",
        "image_url": null,
        "description": "<p><span style=\"font-size:12pt;\"><strong>Informasi tentang PlayStation Network Card US</strong></span>\n<span style=\"font-size:12pt;\"><strong>* Hanya bisa digunakan untuk PlayStation Network Account Region US.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Apa itu PlayStation Network Card ?</strong></span>\n<span style=\"font-size:12pt;\"><strong>PlayStation Store Prepaid Card atau PSN Card adalah voucher pengisian saldo wallet pada akun PlayStation® Network kamu. PSN Card ini juga bisa digunakan sebagai alat pembayaran digital di PSN Store. Dengan PSN wallet, kamu bisa membeli berbagai macam permainan eksklusif, add-on content, film, musik dan lain-lain yang tersedia di PlayStation®Store dan Sony Entertainment Network Store, bisa diakses melalui PS4, PS3 atau PS Vita kamu.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Dimana saya akan menerima Kode PSN Card yang sudah saya beli?</strong></span>\n<span style=\"font-size:12pt;\"><strong>• Kode PSN Card akan dikirim via Pesan Itemku.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Cara Menukarkan Kode PlayStation Gift Card:</strong></span>\n<span style=\"font-size:12pt;\"><strong>Melalui console atau handheld (PS3, PS4, PSVita)</strong></span>\n<span style=\"font-size:12pt;\"><strong>1. Masuk ke menu Playstation Store.</strong></span>\n<span style=\"font-size:12pt;\"><strong>2. Pilih menu Redeem Codes.</strong></span>\n<span style=\"font-size:12pt;\"><strong>3. Masukkan 12 digit kode (harus secara manual, tidak copy paste), klik Continue, dan selesaikan proses.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Melalui browser desktop ataupun smartphone</strong></span>\n<span style=\"font-size:12pt;\"><strong>1. Masuk ke https://account.sonyentertainmentnetwork.com/liquid/login.action</strong></span>\n<span style=\"font-size:12pt;\"><strong>2. Lakukan Sign In.</strong></span>\n<span style=\"font-size:12pt;\"><strong>3. Pilih menu Add Funds.</strong></span>\n<span style=\"font-size:12pt;\"><strong>4. Pilih menu Redeem Prepaid Card.</strong></span>\n<span style=\"font-size:12pt;\"><strong>5. Masukan 12 digit kode dan klik Continue dan selesaikan proses.</strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong> </strong></span></p>\n<p><span style=\"font-size:12pt;\"><strong>Untuk tutorial resmi dari Playstation, silakan cek di https://www.playstation.com/en-us/explore/playstationnetwork/redemption/</strong></span></p>",
        "meta_description": "",
        "price": 670000,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "playstation-network-card-us-50-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2018-05-07 13:54:07",
        "updated_at": "2021-09-06 07:40:28",
        "game": {
          "id": 80,
          "name": "Playstation Network Card",
          "slug": "playstation-network-card",
          "nickname": "PSN Card",
          "seo_string": "Playstation Network Card (PSN)",
          "publisher": "Sony",
          "is_active": 1,
          "is_strict_item_info": 0,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari Transaksi Langsung Dengan Penjual\r\nGunakan Fitur Pesan itemku Dalam Berkomunikasi Dengan Penjual",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20180516/5afbd1cbc2436.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20181011/5bbee915b1ab8.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20180516/5afbd1cb8e596.png",
          "small_icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/20190219/5c6baad5f09c4.png",
          "description": "Tempat Jual-Beli Voucher Game no.1 di Indonesia, paling murah dan terpercaya. Pembelian berbagai macam jenis dan nominal kode voucher game tersedia di itemku.\r\n</br></br>\r\nMulai dari Garena Shell, Gemscool G-Cash, Lyto Game-On, Megaxus Mi-Cash, Battle.net Card, Google Play Gift Card, iTunes Gift Card, Playstation Network Card, Xbox Live Card. Voucher tersebut dapat digunakan untuk isi kredit game populer seperti Cash Point Blank (PB Garena), Dragon Nest, Koin Ragnarok Online Gravindo, RF Online Classic, AyoDance, Overwatch, Gems Clash of Clans (COC), Diamond Mobile Legends & banyak lainnya.\r\n</br></br>\r\nBelanja di itemku sangat aman dan mudah dengan itemku Safe Trading, juga cepat dan praktis verifikasi otomatis 24 jam. Pembayaran tersedia melalui ATM dengan Virtual Account, Cash/Tunai melalui Indomaret, Alfamart, Pegadaian & Kantor Pos, Pulsa Telkomsel, Indosat & XL, serta dengan menggunakan Dana Dompetku.",
          "template_description": "https://itemku.com/tanya-jawab/artikel/cara-trading-e-voucher/235260387 <hr>",
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-e-voucher/235260387",
          "platform_id": null,
          "game_official_store_id": 6,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 196,
          "game_id": 80,
          "name": "Gift Card",
          "slug": "gift-card",
          "seo_string": null,
          "description": null,
          "trade_link": null,
          "sequence": 196,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 1,
          "max_codes": 1,
          "how_to_trade_faq_id": "235035448",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 1,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 2,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 1,
          "allow_image_subtitle": 0,
          "maximum_image_upload": 3,
          "item_category_id": 4,
          "withdrawable_day": 0,
          "is_subscription": 1,
          "risky_type_id": 0,
          "is_using_denom": 1,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": 0,
          "is_using_order_info": 1,
          "ip_address": null,
          "required_info": null
        },
        "item_info": {
          "id": 4927,
          "name": "US$ 50",
          "slug": "us-50",
          "game_id": 80,
          "item_type_id": 196,
          "item_info_group_id": 30,
          "base_unit": 1,
          "max_order": 0,
          "nominal_value": 50,
          "description": "",
          "is_active": 1
        },
        "order_record": {
          "product_id": 369842,
          "successful_order_count": 212,
          "failed_order_count": 1
        },
        "stock": 1,
        "view_count": 1860,
        "images": [
          {
            "id": 1802482,
            "product_id": 369842,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/5d54626509f988e1238d85415c843a2ed641bfcf4f36cb2083fdf9252e663800.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/5d54626509f988e1238d85415c843a2ed641bfcf4f36cb2083fdf9252e663800_thumb.jpg",
            "image_title": null,
            "image_text": null,
            "is_active": 1,
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/5d54626509f988e1238d85415c843a2ed641bfcf4f36cb2083fdf9252e663800_thumb.webp",
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/5d54626509f988e1238d85415c843a2ed641bfcf4f36cb2083fdf9252e663800.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": 755000,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 1,
        "rarity_type_id": null,
        "suggested_price": 674800,
        "use_fast_delivery": 0,
        "use_ads": 0
      },
      {
        "id": 818234,
        "seller_id": 627650,
        "game_id": 171,
        "item_type_id": 433,
        "server_id": 310,
        "item_info_id": 9447,
        "item_info_group_id": 155,
        "item_category_id": 4,
        "use_auto_delivery": 1,
        "is_fast_delivery_set": 0,
        "name": "US $50",
        "image_url": null,
        "description": "Cara Trading Battle.net Gift Card\n\n1. Pilih dagangan dan lakukan pembelian\n2. Terima kode voucher dari penjual\n3. Login ke Battle.net melalui website atau aplikasi\n4. Klik Profile kamu yang terletak di kanan atas\n5. Pilih Redeem A Code dari dropdown menu yang tersedia\n6. Masukkan kode yang sudah kamu terima dari penjual lalu tekan tombol Redeem Code\n7. Periksa apakah Battle.net Balance kamu sudah bertambah sesuai dengan yang kamu beli\n8. Jika sudah sesuai, klik Selesai untuk menyelesaikan pesanan kamu",
        "meta_description": null,
        "price": 669900,
        "min_order": 1,
        "max_order": 0,
        "base_unit": 1,
        "seo_string": "battlenet-us-50-ajp-game-store",
        "is_active": 1,
        "is_group_buy_active": 0,
        "is_ads_active": 0,
        "created_at": "2020-06-22 16:07:59",
        "updated_at": "2021-09-06 07:40:28",
        "game": {
          "id": 171,
          "name": "Battle.net",
          "slug": "battlenet",
          "nickname": "Battle Net",
          "seo_string": "blizzard battle net",
          "publisher": "Activision Blizzard",
          "is_active": 1,
          "is_strict_item_info": 0,
          "sequence": 1,
          "region": "Global",
          "required_information_notice": "Hindari transaksi langsung dengan Penjual. Selalu gunakan Fitur Pesan itemku untuk berkomunikasi.",
          "required_information": null,
          "posting_notice": "Demi keamanan kamu, dilarang memberikan kontak / link pribadi baik (email, telepon, id sosial media) di deskripsi, foto dagangan, foto profile, fitur pesan dan slogan karena tidak sesuai dengan aturan penggunaan itemku. Jika kamu tetap melakukannya maka akun kamu akan dinonaktifkan.",
          "banner_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020327/yutvah6otn3on8bkmi4l6.png",
          "poster_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020327/ty53gi4v148yzk7f08ikff.png",
          "icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020327/2wsdkejiafxaj71qg5950c.png",
          "small_icon_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/game/2020327/2wsdkejiafxaj71qg5950c_thumbnail.png",
          "description": "Battle.net adalah platform game seperti Steam yang dimiliki oleh Activision Blizzard. Mainkan game-game keluaran Blizzard dan Activision seperti World of Warcraft, Overwatch, Call of Duty (CoD). Gunakan voucher Battle.net gift card untuk belanja game atau kebutuh skin, kosmetik, dan Battle Pass kamu.",
          "template_description": null,
          "how_to_trade_link": "https://itemku.com/tanya-jawab/artikel/cara-trading-battle.net/360041562971",
          "platform_id": null,
          "game_official_store_id": 9,
          "official_store_placeholder_json": null,
          "can_update_product": 1,
          "visibility_status": 0,
          "is_physical_item": 0
        },
        "item_type": {
          "id": 433,
          "game_id": 171,
          "name": "Gift Card",
          "slug": "gift-card",
          "seo_string": null,
          "description": null,
          "trade_link": null,
          "sequence": 99,
          "has_single_item_info": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "is_itemku_point_eligible": 0,
          "max_codes": 1,
          "how_to_trade_faq_id": "360041562971",
          "is_active": 1,
          "use_default_instruction": 1,
          "image_is_mandatory": 0,
          "transaction_fixed_fee": 0,
          "transaction_percentage_fee": 2,
          "transaction_max_fee": 0,
          "buyer_fixed_fee": 0,
          "buyer_percentage_fee": 0,
          "default_sort": 1,
          "allow_image_subtitle": 1,
          "maximum_image_upload": 3,
          "item_category_id": 4,
          "withdrawable_day": 0,
          "is_subscription": 1,
          "risky_type_id": 0,
          "is_using_denom": 1,
          "moderation_type_id": 0,
          "allow_refund_request_time": 2,
          "delivery_due_time": 6,
          "required_information_field_id": null,
          "is_using_order_info": 1,
          "ip_address": null,
          "required_info": null
        },
        "item_info": {
          "id": 9447,
          "name": "US $50",
          "slug": "us-50",
          "game_id": 171,
          "item_type_id": 433,
          "item_info_group_id": 155,
          "base_unit": 1,
          "max_order": 0,
          "nominal_value": 50,
          "description": null,
          "is_active": 1
        },
        "order_record": {
          "product_id": 818234,
          "successful_order_count": 93,
          "failed_order_count": 0
        },
        "stock": 1,
        "view_count": 583,
        "images": [
          {
            "id": 1802544,
            "product_id": 818234,
            "sequence": 1,
            "image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/92e8025e4c8b650ad57fc75a1d4aeb59bd7b994d5bb9a7fb2886aad513e290d0.jpg",
            "thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/92e8025e4c8b650ad57fc75a1d4aeb59bd7b994d5bb9a7fb2886aad513e290d0_thumb.jpg",
            "image_title": "battlenet",
            "image_text": "",
            "is_active": 1,
            "alternate_thumbnail_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/92e8025e4c8b650ad57fc75a1d4aeb59bd7b994d5bb9a7fb2886aad513e290d0_thumb.webp",
            "alternate_image_url": "https://d1x91p7vw3vuq8.cloudfront.net/web/20200805/92e8025e4c8b650ad57fc75a1d4aeb59bd7b994d5bb9a7fb2886aad513e290d0.webp"
          }
        ],
        "wholesale": [

        ],
        "competitor_price": null,
        "market_price": null,
        "seller": {
          "id": 627650,
          "shop_name": "AJP Game Store",
          "average_rating": 4.88,
          "rating_count": 25226,
          "average_delivery_time": -66585,
          "is_active": 1,
          "is_open": 1,
          "is_banned": 0,
          "has_auto_delivery": 1,
          "is_fast_delivery_eligible": 0,
          "can_sell_topup": 1,
          "can_sell_account": 0,
          "can_sell_physical_item": 0,
          "can_use_ads": 0
        },
        "seller_emblem": null,
        "server_name": "",
        "is_cheaper_than_competitor": 0,
        "rarity_type_id": null,
        "suggested_price": 0,
        "use_fast_delivery": 0,
        "use_ads": 0
      }
    ],
    "total_item": 44,
    "item_per_page": 10,
    "current_page": 1
  },
  "message": "Success",
  "statusCode": "SUCCESS"
}